export default {
  PHONELIST: {
    FETCH_REQUEST: "PHONELIST/FETCH_REQUEST",
    FETCH_SUCCESS: "PHONELIST/FETCH_SUCCESS",
    FETCH_FAILURE: "PHONELIST/FETCH_FAILURE",
    SELECT_FOR_DETAILS: "PHONELIST/SELECT_FOR_DETAILS",
    RESET_DETAILS: "PHONELIST/RESET_DETAILS"
  }
};
